#!/bin/bash

read -p "Créer commitInfo.txt pour ce commit (y/[n]) ? " yn < /dev/tty
yn=${yn:n}

case $yn in
  [Yy]* )
    mkdir -p suivi
    echo "commit vérifié le $(date '+%Y-%m-%d %H:%M:%S')" > suivi/commitInfo.txt
    git add suivi/commitInfo.txt
    ;;
  * )
    ;;
esac

exit 0
